name: sdk
description: >
  Utilities for finding and using the Dart SDK
version: 0.1.0
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/sdk.dart

dependencies:
  path: '^1.4.1'
  pub_semver: '^1.3.2'

dev_dependencies:
  test: '^0.12.18+1'
